ai:
  model: "deepseek/deepseek-r1-0528-qwen3-8b:free"
  base_url: "https://openrouter.ai/api/v1/chat/completions"
  language: "Russian"
  prompt_messages: [
    {
      "role": "system",
      "content": "You create affirmations based on the task from the Task Tracker. 
      You always answer in {{ language }} language. 
      Answer only 1 sentence affirmations without text format. 
      The task: {{ task }}"
    }
  ]