"""notification-datetime2time

Revision ID: 6d8097c9df7a
Revises: 559e75d01aba
Create Date: 2025-09-30 23:25:00.231238

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6d8097c9df7a'
down_revision: Union[str, Sequence[str], None] = '559e75d01aba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'notifications', 'scheduled_for',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.Time(),
        existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema (time -> timestamp)."""
    op.alter_column(
        'notifications',
        'scheduled_for',
        existing_type=sa.Time(),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        postgresql_using="'1970-01-01'::date + scheduled_for"
    )
