"""notification-track-start-finish

Revision ID: 6857f916dc25
Revises: 6d8097c9df7a
Create Date: 2025-09-30 23:40:02.331462

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6857f916dc25'
down_revision: Union[str, Sequence[str], None] = '6d8097c9df7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('started_at', sa.DateTime(), nullable=True))
    op.add_column('notifications', sa.Column('finished_at', sa.DateTime(), nullable=True))
    op.add_column('notifications', sa.Column('status', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'status')
    op.drop_column('notifications', 'finished_at')
    op.drop_column('notifications', 'started_at')
    # ### end Alembic commands ###
